# Generated by Django 2.0 on 2017-12-12 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('publishing', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('date_in', models.DateTimeField()),
                ('quantity_in', models.IntegerField()),
                ('quantity_out', models.IntegerField()),
                ('quantity_loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_borrow', models.DateField()),
                ('data_return', models.DateField()),
                ('loss', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Book')),
            ],
        ),
        migrations.CreateModel(
            name='LossReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=5)),
                ('days', models.IntegerField()),
                ('numbers', models.IntegerField()),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(max_length=5)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('card_name', models.CharField(max_length=8)),
                ('card_id', models.CharField(max_length=20)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.MemberLevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lossreporting',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Profile'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.BookCategory'),
        ),
    ]
