# Generated by Django 2.0 on 2017-12-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.BookCategory'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Profile'),
        ),
        migrations.AlterField(
            model_name='lossreporting',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.MemberLevel'),
        ),
    ]
