# Generated by Django 2.0 on 2017-12-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20171212_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='egistrationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
