# Generated by Django 2.0 on 2017-12-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_profile_egistrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossreporting',
            name='loss_date',
            field=models.DateField(),
        ),
    ]
