# Generated by Django 2.0 on 2017-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20171212_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_in',
            field=models.DateField(),
        ),
    ]
