# Generated by Django 2.0 on 2017-12-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_borrow_is_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='data_borrow',
            new_name='date_borrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='data_return',
            new_name='date_return',
        ),
    ]
