# Generated by Django 2.0 on 2017-12-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20171221_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='loss',
            new_name='is_lost',
        ),
    ]
