# Generated by Django 2.0 on 2017-12-22 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20171221_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='date_borrow',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
