# Generated by Django 2.0 on 2017-12-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
